### ISSUE TITLE
pandoc_download should check architecture

### ISSUE THREAD

**Issue by zachriggle** [NicklasTegner/pypandoc#125]
The code for `pandoc_download` does not check the current architecture.

This means that you can run `pandoc_download` on e.g. a Raspberry Pi, and it'll download the `amd64` distribution of Pandoc, and attempt to install it.

This ends up throwing a non-descriptive `RuntimeError` somewhere along the way.

Pandoc should check the current architecture in `pandoc_download`, and throw an exception (or similar) if a distribution is unavailable.

See Gallopsled/pwntools#820

**Comment by ickc** [comment]
Some comments on this issue (not an expert here, so what I said might not make sense):

- the `pandoc_urls` format shouldn't need to be changed, because there's not other alternative `.deb` binaries provided so far, and it seems to me there's no plan to provide them in the future.

- to get the architecture, <http://stackoverflow.com/a/7171315> seems to help. But I don't have non-amd64 linux machine to test.

- It might be easier to catch the RuntimeError and emit error msg from there.

*If we want to improve the situation to provide support on platforms that pandoc don't provide a binary*:

- We can tell the system to install from existing package manager, e.g. apt-get on Raspberry Pi (which has a successful report in [pandoc-discuss/Install pandoc on Raspberry Pi ARM](https://groups.google.com/d/msg/pandoc-discuss/sGcUpLVmLnk/Qoh79_VhCQAJ)).

	- This seems manageable, but need to lookup different package manager from Linux variants. See [Pandoc - Installing pandoc](http://pandoc.org/installing.html#linux) for the supported Linux variants.

	- I see that pypandoc is available through conda too. Using system's package manager could be a problem in this case.

- If built from source (which I think is too complicated, but *might* fit conda better), references:

	- [Homebrew/homebrew-core/pandoc.rb](https://github.com/Homebrew/homebrew-core/blob/master/Formula/pandoc.rb) can be a good reference. (While homebrew is for macOS, there's a linux brew variants for linux. And the brew-formula could be learnt and converted into native Python instructions.)

	- (very old) For Raspberry Pi, see [Building pandoc on a Raspberry Pi 1 Model B · jgm/pandoc Wiki](https://github.com/jgm/pandoc/wiki/Building-pandoc-on-a-Raspberry-Pi-1-Model-B).

**Comment by ickc** [comment]
Additional comment: I can see there's a need to check a matching architecture — before download rather than getting `RuntimeError` when trying installing — to avoid unnecessary download.

But the checking can be hardcoded rather then adding into the dict, for the same reason said above that there seems no plan for pandoc to provide binaries for other Linux architecture.

**Comment by janschulz** [comment]
Currently pypandoc only download what is available in the official pandoc releases. As long as they do not have binaries for somethign else than linux-amd64, we can't add other architectures.

One could add a check for the right archtecture so that it fails earlier, but thats the best we can do right now without building pandoc itself or getting other channels to download it from :-(

```python 
>>> platform.machine()
'x86_64'
```
