### ISSUE TITLE
Creating a pypandoc-binary

### ISSUE THREAD

**Issue by AbdealiJK** [NicklasTegner/pypandoc#279]
I have been using pypandoc for a while now, and I always create a .whl with pandoc present in it as it's much easier to use.

It would be great if this package can hev:
 - pypandoc
 - pypandoc-binary
packages in pypi.

Somewhat like how the pysqlite3 project does it:
https://pypi.org/project/pysqlite3-binary/
https://pypi.org/project/pysqlite3/

That would help a lot for folks who just want to get a working version of pandoc directly without mucking around with system level dependencies.

**Comment by NicklasTegner** [comment]
This is a good idea.
I see 2 ways to do this:

* Do it you suggested, with 2 different versions
* Or by using extras so it becomes pip install pypandoc[binary] or poetry add pypandoc -E binary (or binaries)

What do you think?

**Comment by AbdealiJK** [comment]
I don't mind either.
But I'm not sure how the extras one would work.
As my understanding is that extras can only add additional "extra_requires" which adds extra dependencies.

Atleast I'm not aware if it can also have extra files.
So maybe for both cases a pypandoc-binary could be required which is then added to a extra_requires ?

**Comment by NicklasTegner** [comment]
I like the pypandoc_binaries option then.

The following would need to be done (at least)

* Make setup.py and setup_binaries.py file.
* This would also give us the chance to clean up the regular setup.py file, since download_pandoc wouldn't be required in the smaller version.
* Update the CI scripts

Do let me know if you think I've missed something
