### ISSUE TITLE
Make sure that the dir of the pandoc executable is in PATH

### ISSUE THREAD

**Issue by jankatins** [NicklasTegner/pypandoc#97]
We also install citeproc and there is a high probability that next to pandoc other filters are installed. So let's make sure that pandoc finds these.

If pandoc currently does not look into that dir: if we have a full path for pandoc (=Not in PATH), we should add that dir to the PATH as well before calling pandoc.

**Comment by scottclowe** [comment]
At the moment, if you run `download_pandoc` or `ensure_pandoc_installed` with `targetfolder` manually specified to a directory not on the PATH, that directory is not added to the PATH. These means that calls to `convert_file` (etc) will fail.

I think `ensure_pandoc_installed` should add the `targetfolder` to PATH using `os.environ["PATH"]` if it isn't already on the PATH. Otherwise it hasn't actually ensured that pandoc is installed.
